UPDATE yieldslab
SET region = 
CASE WHEN region = '14' THEN $$EMBU$$
WHEN region = '05' THEN $$Iburasirazuba$$
WHEN region = '33' THEN $$NAROK$$
WHEN region = '18' THEN $$NYANDARUA$$
WHEN region = '26' THEN $$TRANS NZOIA$$
WHEN region = '03' THEN $$Iburengerazuba$$
WHEN region = '13' THEN $$THARAKA - NITHI$$
WHEN region = '04' THEN $$Amajyaruguru$$
WHEN region = '25' THEN $$SAMBURU$$
WHEN region = '29' THEN $$NANDI$$
WHEN region = '28' THEN $$ELGEYO/MARAKWET$$
WHEN region = '07' THEN $$GARISSA$$
WHEN region = '11' THEN $$ISIOLO$$
WHEN region = '32' THEN $$NAKURU$$
WHEN region = '17' THEN $$MAKUENI$$
WHEN region = '08' THEN $$WAJIR$$
WHEN region = '31' THEN $$LAIKIPIA$$
WHEN region = '47' THEN $$NAIROBI$$
WHEN region = '20' THEN $$KIRINYAGA$$
WHEN region = '30' THEN $$BARINGO$$
WHEN region = '27' THEN $$UASIN GISHU$$
WHEN region = '43' THEN $$HOMA BAY$$
WHEN region = '09' THEN $$MANDERA$$
WHEN region = '35' THEN $$KERICHO$$
WHEN region = '22' THEN $$KIAMBU$$
WHEN region = '46' THEN $$NYAMIRA$$
WHEN region = '45' THEN $$KISII$$
WHEN region = '16' THEN $$MACHAKOS$$
WHEN region = '10' THEN $$MARSABIT$$
WHEN region = '38' THEN $$VIHIGA$$
WHEN region = '37' THEN $$KAKAMEGA$$
WHEN region = '41' THEN $$SIAYA$$
WHEN region = '12' THEN $$MERU$$
WHEN region = '15' THEN $$KITUI$$
WHEN region = '23' THEN $$TURKANA$$
WHEN region = '42' THEN $$KISUMU$$
WHEN region = '01' THEN $$Umujyi wa Kigali$$
WHEN region = '34' THEN $$KAJIADO$$
WHEN region = '06' THEN $$TAITA TAVETA$$
WHEN region = '39' THEN $$BUNGOMA$$
WHEN region = '36' THEN $$BOMET$$
WHEN region = '21' THEN $$MURANG'A$$
WHEN region = '40' THEN $$BUSIA$$
WHEN region = '24' THEN $$WEST POKOT$$
WHEN region = '19' THEN $$NYERI$$
WHEN region = '02' THEN $$Amajyepfo$$
WHEN region = '44' THEN $$MIGORI$$
ELSE region END;

